plugins {
    id 'java'
    id 'maven-publish'
}

group = 'ospx'
def baseVersion = '1.6'
version = findProperty('xcorePublishVersion') ?: baseVersion
ext {
    mindustryVersion = "v159"
}

def xcoreSnapshotsRepositoryUrl = findProperty('xcoreMavenSnapshotsUrl') ?: 'https://maven.x-core.org/snapshots'
def xcoreReleasesRepositoryUrl = findProperty('xcoreMavenReleasesUrl') ?: 'https://maven.x-core.org/releases'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url "https://maven.x-core.org/releases" }
    maven { url "https://maven.x-core.org/snapshots" }
    maven { url "https://maven.xpdustry.com/mindustry" }
    maven { url "https://raw.githubusercontent.com/Zelaux/MindustryRepo/master/repository" }
    maven { url 'https://www.jitpack.io' }
}

publishing {
    repositories {
        maven {
            name = "xcoreRepositorySnapshots"
            url = uri(xcoreSnapshotsRepositoryUrl)
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }

        maven {
            name = "xcoreRepositoryReleases"
            url = uri(xcoreReleasesRepositoryUrl)
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
    publications {
        maven(MavenPublication) {
            groupId = "com.ospx"
            artifactId = "flubundle"
            version = project.version
            from components.java
        }
    }
}

dependencies {
    compileOnly "com.github.Anuken.Mindustry:core:$mindustryVersion"
    compileOnly "com.github.Anuken.Arc:arc-core:$mindustryVersion"

    implementation "net.xyzsd.fluent:fluent-base:2.0.1-xcore"

    testImplementation platform('org.junit:junit-bom:6.1.3')
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation "com.github.Anuken.Mindustry:core:$mindustryVersion"
    testImplementation "com.github.Anuken.Arc:arc-core:$mindustryVersion"
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
