package com.ospx.flubundle.compiler;

import com.ospx.flubundle.LocaleCodes;
import com.ospx.flubundle.MessageVariables;
import fluent.syntax.ast.Entry;
import fluent.syntax.ast.Message;
import fluent.syntax.parser.FTLParser;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeMap;

/**
 * Generates a Java class with one {@code String} constant per message of the base locale, so that
 * a renamed or deleted key breaks compilation instead of showing the raw key to players.
 *
 * <pre>{@code
 * // generated from bundles/bundle_en.ftl
 * public final class BundleKeys {
 *     // Javadoc lists the variables: $seconds
 *     public static final String HEXED_COUNTDOWN_TICK = "hexed_countdown_tick";
 * }
 * }</pre>
 *
 * <p>Run it from the build with {@link #main(String[])}:
 * {@code KeyConstantsGenerator <bundles-dir> <package> <class> <output-source-root> [base-locale]}.
 */
public final class KeyConstantsGenerator {

    private KeyConstantsGenerator() {
    }

    public static void main(String[] args) throws IOException {
        if (args == null || args.length < 4) {
            System.err.println("Usage: KeyConstantsGenerator <bundles-dir> <package> <class> <output-source-root> [base-locale]");
            System.exit(1);
        }

        var file = write(Path.of(args[0]), args.length > 4 ? args[4] : "en", args[1], args[2], Path.of(args[3]));
        System.out.println("Generated " + file);
    }

    /**
     * Generates the class and writes it under {@code outputRoot}, in the directory of its package.
     *
     * @return the written file
     */
    public static Path write(Path directory, String baseLocale, String packageName, String className,
                             Path outputRoot) throws IOException {
        var source = generate(directory, baseLocale, packageName, className);
        var packageDir = packageName.isEmpty() ? outputRoot : outputRoot.resolve(packageName.replace('.', '/'));
        Files.createDirectories(packageDir);
        var file = packageDir.resolve(className + ".java");
        if (!Files.exists(file) || !Files.readString(file, StandardCharsets.UTF_8).equals(source)) {
            Files.writeString(file, source, StandardCharsets.UTF_8);
        }
        return file;
    }

    /**
     * @return Java source of a final class with a constant for each message of the base locale
     * @throws IllegalStateException if no base locale files exist or two keys map to one constant name
     */
    public static String generate(Path directory, String baseLocale, String packageName, String className) {
        Objects.requireNonNull(packageName, "packageName");
        Objects.requireNonNull(className, "className");
        var base = Objects.requireNonNull(LocaleCodes.normalize(baseLocale), "baseLocale must not be blank");
        var messages = loadMessages(directory, base);
        if (messages.isEmpty()) {
            throw new IllegalStateException("No messages for base locale '" + base + "' in " + directory);
        }

        var constants = new TreeMap<String, String>();
        for (var key : messages.keySet()) {
            var name = constantName(key);
            var previous = constants.put(name, key);
            if (previous != null) {
                throw new IllegalStateException("Keys '" + previous + "' and '" + key + "' both map to constant " + name);
            }
        }

        var out = new StringBuilder();
        if (!packageName.isEmpty()) {
            out.append("package ").append(packageName).append(";\n\n");
        }
        out.append("/** Message keys of locale '").append(base)
                .append("'. Generated by FluBundle KeyConstantsGenerator; do not edit. */\n");
        out.append("public final class ").append(className).append(" {\n\n");
        out.append("    private ").append(className).append("() {\n    }\n");

        for (var entry : constants.entrySet()) {
            var key = entry.getValue();
            var variables = MessageVariables.of(messages.get(key), messages::get);
            out.append('\n');
            if (!variables.isEmpty()) {
                out.append("    /** Variables: ").append(describe(variables)).append(". */\n");
            }
            out.append("    public static final String ").append(entry.getKey())
                    .append(" = \"").append(key).append("\";\n");
        }
        out.append("}\n");
        return out.toString();
    }

    /** {@code player-joined} and {@code player_joined} become {@code PLAYER_JOINED}. */
    static String constantName(String key) {
        var name = new StringBuilder();
        for (int i = 0; i < key.length(); i++) {
            char c = key.charAt(i);
            name.append(Character.isLetterOrDigit(c) ? Character.toUpperCase(c) : '_');
        }
        if (name.isEmpty() || Character.isDigit(name.charAt(0))) {
            name.insert(0, '_');
        }
        return name.toString().toUpperCase(Locale.ROOT);
    }

    private static String describe(Set<String> variables) {
        var parts = new ArrayList<String>();
        for (var variable : variables) {
            parts.add("{@code $" + variable + "}");
        }
        return String.join(", ", parts);
    }

    private static Map<String, Message> loadMessages(Path directory, String baseLocale) {
        List<Path> files;
        try (var stream = Files.walk(directory)) {
            files = stream.filter(f -> f.toString().endsWith(".ftl")).sorted().toList();
        } catch (IOException e) {
            throw new IllegalStateException("Failed to scan directory: " + directory, e);
        }

        var messages = new LinkedHashMap<String, Message>();
        for (var file : files) {
            var name = file.getFileName().toString();
            var code = LocaleCodes.normalize(LocaleCodes.fromFileName(name.substring(0, name.length() - ".ftl".length())));
            if (!baseLocale.equals(code)) {
                continue;
            }

            String content;
            try {
                content = Files.readString(file, StandardCharsets.UTF_8);
            } catch (IOException e) {
                throw new IllegalStateException("Failed to read " + file, e);
            }

            for (Entry entry : FTLParser.parse(content).entries()) {
                if (entry instanceof Message message) {
                    messages.put(message.identifier().name(), message);
                }
            }
        }
        return messages;
    }
}
