import com.ospx.flubundle.compiler.KeyConstantsGenerator;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class KeyConstantsGeneratorTest {

    @TempDir
    Path dir;

    @Test
    void generatesSortedConstantsWithVariablesFromBaseLocaleOnly() throws IOException {
        Files.writeString(dir.resolve("bundle_en.ftl"), """
                -brand = XCore
                player-joined = { $player } joined { -brand }
                hexed_countdown_tick = { $seconds } s
                plain = Text
                """);
        Files.writeString(dir.resolve("bundle_ru.ftl"), "only-ru = Только\n");

        String source = KeyConstantsGenerator.generate(dir, "en", "org.example", "BundleKeys");

        assertEquals("""
                package org.example;

                /** Message keys of locale 'en'. Generated by FluBundle KeyConstantsGenerator; do not edit. */
                public final class BundleKeys {

                    private BundleKeys() {
                    }

                    /** Variables: {@code $seconds}. */
                    public static final String HEXED_COUNTDOWN_TICK = "hexed_countdown_tick";

                    public static final String PLAIN = "plain";

                    /** Variables: {@code $player}. */
                    public static final String PLAYER_JOINED = "player-joined";
                }
                """, source);
    }

    @Test
    void rejectsKeysThatCollide() throws IOException {
        Files.writeString(dir.resolve("bundle_en.ftl"), "a-b = 1\na_b = 2\n");

        var error = assertThrows(IllegalStateException.class,
                () -> KeyConstantsGenerator.generate(dir, "en", "p", "K"));
        assertTrue(error.getMessage().contains("A_B"));
    }

    @Test
    void rejectsMissingBaseLocale() throws IOException {
        Files.writeString(dir.resolve("bundle_ru.ftl"), "a = 1\n");

        assertThrows(IllegalStateException.class, () -> KeyConstantsGenerator.generate(dir, "en", "p", "K"));
    }

    @Test
    void writesIntoPackageDirectoryAndSkipsUnchangedFiles() throws IOException {
        Path bundles = Files.createDirectories(dir.resolve("bundles"));
        Files.writeString(bundles.resolve("bundle_en.ftl"), "a = 1\n");
        Path out = dir.resolve("generated");

        Path file = KeyConstantsGenerator.write(bundles, "en", "org.example.i18n", "Keys", out);
        assertEquals(out.resolve("org/example/i18n/Keys.java"), file);
        var modified = Files.getLastModifiedTime(file);

        Files.setLastModifiedTime(file, java.nio.file.attribute.FileTime.fromMillis(0));
        KeyConstantsGenerator.write(bundles, "en", "org.example.i18n", "Keys", out);
        assertEquals(0, Files.getLastModifiedTime(file).toMillis(), "unchanged output is not rewritten");
        assertFalse(modified.toMillis() == 0);
    }
}
