name: Publish to XCore Repository

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Publish
        run: |
          chmod +x gradlew
          ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_xcoreRepositoryUsername: ${{ secrets.XCORE_USERNAME }}
          ORG_GRADLE_PROJECT_xcoreRepositoryPassword: ${{ secrets.XCORE_PASSWORD }}
